server:
  port: 8890

logging:
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'DEBUG'

security:
  user:
    name: admin
    password: secret
    roles: SUPERUSER



spring:
  application:
    name: developer
  datasource:
    url: jdbc:postgresql://localhost:5432/mini_eva
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: cn.eva.mini.infra.db.dialect.JSONBPostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: updater
  redis:
    host: localhost
    port: 6379
  mail:
    protocol: smtp
    host: smtp.gmail.com
    port: 587
    username: email
    password: password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

message:
  broker:
    host: 127.0.0.1
    port: 1883
    username: umasuo
    password: password